# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Github Releases"
  lane :beta do |options|
    puts options[:version]
    gradle(task: "clean assembleRelease")
    if not options[:skip_release]
      set_github_release(
      repository_name: "RanderGabriel/newschool-app",
      api_token: ENV["GITHUB_TOKEN"],
      name: options[:name],
      tag_name: options[:version],
      description: (File.read("changelog") rescue "No changelog provided"),
      commitish: "master",
      upload_assets: [lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]]
      )
    end
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
